{
  "// 适用版本": "ClashMi",
  "// 语法标准": "严格 ES5 降级，完美兼容内置 JS 引擎",
  "config[\"external-controller\"] = \"127.0.0.1": "9090\";",
  "\"enable\"": false,
  "\"device\"": "Clash Mi\", // ClashMi 平台必须指定该设备",
  "\"stack\"": "gvisor\", // 移动端建议使用 gvisor 栈以获得最佳内存控制，避免 50M 溢出崩",
  "\"dns-hijack\"": "[\"any:53\", \"tcp://any:53\"],",
  "\"auto-route\"": "true,",
  "\"auto-detect-interface\"": "false, // 移动端建议设为 false，防止由于网络频繁切换导致异常",
  "\"strict-route\"": "true, // 核心：开启严格路由防止 DNS 泄露",
  "\"endpoint-independent-nat\"": "true,",
  "\"mtu\"": "4064, // ClashMi 优化 MTU",
  "\"inet4-address\"": "[\"172.19.0.1/30\"], // ClashMi 默认 TUN 网段",
  "\"auto-redirect\"": "false,",
  "\"route-exclude-address\"": "[",
  "\"fe80": ":/10\",",
  "\"ff00": ":/8\",",
  "\"": ":1/128\"",
  "\"store-selected\"": "true,",
  "\"store-fake-ip\"": true,
  "\"geoip\"": "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.dat\"",
  "\"geosite\"": "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geosite.dat\"",
  "\"mmdb\"": "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/country.mmdb\"",
  "\"asn\"": "https://github.com/xishang0128/geoip/releases/download/latest/GeoLite2-ASN.mmdb",
  "\"prefer-h3\"": "true, // 开启 DoH 的 HTTP/3 握手支持",
  "\"ipv6\"": "true, // 允许解析 AAAA 记录",
  "\"ipv6-timeout\"": "300,",
  "\"use-hosts\"": "true,",
  "\"use-system-hosts\"": "true,",
  "\"respect-rules\"": "true, // 严格遵守规则，防 DNS 泄漏",
  "\"enhanced-mode\"": "fake-ip\"",
  "\"fake-ip-range\"": "198.18.0.1/16\"",
  "\"fake-ip-filter-mode\"": "blacklist\"",
  "\"cache-algorithm\"": "arc\"",
  "\"fake-ip-filter\"": "[",
  "\"default-nameserver\"": "[\"223.5.5.5\", \"119.29.29.29\"],",
  "\"nameserver\"": "[\"https://8.8.8.8/dns-query\", \"https://1.1.1.1/dns-query\"],",
  "\"proxy-server-nameserver\"": "[\"https://223.5.5.5/dns-query\", \"119.29.29.29\"],",
  "\"nameserver-policy\"": "{",
  "\"geosite": "cn,private\": [\"https://223.5.5.5/dns-query\", \"119.29.29.29\"]",
  "var proxyUrlPrefix = \"https": "//gh-proxy.com/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo\";",
  "\"webrtc-stun\"": "{ \"type\": \"http\", \"format\": \"mrs\", \"behavior\": \"domain\", \"url\": proxyUrlPrefix + \"/geosite/stun.mrs\", \"path\": \"./ruleset/stun.mrs\", \"interval\": 86400 },",
  "\"category-ads-all\"": "{ \"type\": \"http\", \"format\": \"mrs\", \"behavior\": \"domain\", \"url\": proxyUrlPrefix + \"/geosite/category-ads-all.mrs\", \"path\": \"./ruleset/category-ads-all.mrs\", \"interval\": 86400 },",
  "\"category-ai-!cn\"": "{ \"type\": \"http\", \"format\": \"mrs\", \"behavior\": \"domain\", \"url\": proxyUrlPrefix + \"/geosite/category-ai-!cn.mrs\", \"path\": \"./ruleset/category-ai-!cn.mrs\", \"interval\": 86400 },",
  "\"youtube\"": "{ \"type\": \"http\", \"format\": \"mrs\", \"behavior\": \"domain\", \"url\": proxyUrlPrefix + \"/geosite/youtube.mrs\", \"path\": \"./ruleset/youtube.mrs\", \"interval\": 86400 },",
  "\"google\"": "{ \"type\": \"http\", \"format\": \"mrs\", \"behavior\": \"domain\", \"url\": proxyUrlPrefix + \"/geosite/google.mrs\", \"path\": \"./ruleset/google.mrs\", \"interval\": 86400 },",
  "\"cn\"": "{ \"type\": \"http\", \"format\": \"mrs\", \"behavior\": \"domain\", \"url\": proxyUrlPrefix + \"/geosite/cn.mrs\", \"path\": \"./ruleset/cn.mrs\", \"interval\": 86400 },",
  "\"github\"": "{ \"type\": \"http\", \"format\": \"mrs\", \"behavior\": \"domain\", \"url\": proxyUrlPrefix + \"/geosite/github.mrs\", \"path\": \"./ruleset/github.mrs\", \"interval\": 86400 },",
  "\"microsoft\"": "{ \"type\": \"http\", \"format\": \"mrs\", \"behavior\": \"domain\", \"url\": proxyUrlPrefix + \"/geosite/microsoft.mrs\", \"path\": \"./ruleset/microsoft.mrs\", \"interval\": 86400 },",
  "\"apple\"": "{ \"type\": \"http\", \"format\": \"mrs\", \"behavior\": \"domain\", \"url\": proxyUrlPrefix + \"/geosite/apple.mrs\", \"path\": \"./ruleset/apple.mrs\", \"interval\": 86400 },",
  "\"twitter\"": "{ \"type\": \"http\", \"format\": \"mrs\", \"behavior\": \"domain\", \"url\": proxyUrlPrefix + \"/geosite/twitter.mrs\", \"path\": \"./ruleset/twitter.mrs\", \"interval\": 86400 },",
  "\"netflix\"": "{ \"type\": \"http\", \"format\": \"mrs\", \"behavior\": \"domain\", \"url\": proxyUrlPrefix + \"/geosite/netflix.mrs\", \"path\": \"./ruleset/netflix.mrs\", \"interval\": 86400 },",
  "\"okx\"": "{ \"type\": \"http\", \"format\": \"mrs\", \"behavior\": \"domain\", \"url\": proxyUrlPrefix + \"/geosite/okx.mrs\", \"path\": \"./ruleset/okx.mrs\", \"interval\": 86400 },",
  "\"binance\"": "{ \"type\": \"http\", \"format\": \"mrs\", \"behavior\": \"domain\", \"url\": proxyUrlPrefix + \"/geosite/binance.mrs\", \"path\": \"./ruleset/binance.mrs\", \"interval\": 86400 },",
  "\"kraken\"": "{ \"type\": \"http\", \"format\": \"mrs\", \"behavior\": \"domain\", \"url\": proxyUrlPrefix + \"/geosite/kraken.mrs\", \"path\": \"./ruleset/kraken.mrs\", \"interval\": 86400 },",
  "\"private-ip\"": "{ \"type\": \"http\", \"format\": \"mrs\", \"behavior\": \"ipcidr\", \"url\": proxyUrlPrefix + \"/geoip/private.mrs\", \"path\": \"./ruleset/private-ip.mrs\", \"interval\": 86400 },",
  "\"cn-ip\"": "{ \"type\": \"http\", \"format\": \"mrs\", \"behavior\": \"ipcidr\", \"url\": proxyUrlPrefix + \"/geoip/cn.mrs\", \"path\": \"./ruleset/cn-ip.mrs\", \"interval\": 86400 },",
  "\"telegram-ip\"": "{ \"type\": \"http\", \"format\": \"mrs\", \"behavior\": \"ipcidr\", \"url\": proxyUrlPrefix + \"/geoip/telegram.mrs\", \"path\": \"./ruleset/telegram-ip.mrs\", \"interval\": 86400 }",
  "{ \"name\"": "🏠 私有网络\", \"type\": \"select\", \"proxies\": [\"DIRECT\", \"🚀 节点选择\", \"⚡ 自动选择\", \"🖐️ 手动切换\"] ",
  "\"name\"": "groupName,",
  "\"type\"": "select\"",
  "\"include-all\"": "true,",
  "\"filter\"": "(?i)\" + region.regex",
  "\"url\"": "https://edge.microsoft.com/captiveportal/generate_204\"",
  "\"interval\"": "600,",
  "\"timeout\"": "5000,",
  "\"lazy\"": "true,",
  "\"max-failed-times\"": "2,",
  "\"expected-status\"": "204,",
  "\"tolerance\"": 50,
  "\"proxies\"": "groupProxies",
  "\"geosite_url\"": "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite\"",
  "\"geoip_url\"": "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geoip\"",
  "\"asn_url\"": "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/asn\"",
  "\"update-interval\"": "172800,",
  "\"enable-proxy\"": true,
  "\"bypass_domain\"": "["
}
